name: abxfit
description: A Flutter app for fitness tracking

dependencies:
  flutter:
    sdk: flutter
  firebase_core: latest_version
  firebase_auth: latest_version
  cloud_firestore: latest_version
  provider: latest_version
